
CREATE TABLE COMPANY_EMP_MASTER (
    EMP_ID       NUMBER PRIMARY KEY,
    EMP_NAME     VARCHAR2(50),
    DEPT_ID      NUMBER,
    SALARY       NUMBER,
    STATUS       VARCHAR2(20)
);

CREATE TABLE COMPANY_DEPT_MASTER (
    DEPT_ID      NUMBER PRIMARY KEY,
    DEPT_NAME    VARCHAR2(50),
    LOCATION     VARCHAR2(50)
);




CREATE TABLE COMPANY_EMP_AUDIT_LOG (
    LOG_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EMP_ID       NUMBER,
    OLD_SALARY   NUMBER,
    NEW_SALARY   NUMBER,
    UPDATED_ON   DATE
);


INSERT INTO COMPANY_DEPT_MASTER VALUES (101, 'IT', 'HYDERABAD');
INSERT INTO COMPANY_DEPT_MASTER VALUES (102, 'HR', 'CHENNAI');
INSERT INTO COMPANY_DEPT_MASTER VALUES (103, 'SALES', 'MUMBAI');
INSERT INTO COMPANY_DEPT_MASTER VALUES (104, 'FINANCE', 'BANGALORE');
INSERT INTO COMPANY_EMP_MASTER VALUES (1, 'Rahul', 101, 60000, 'ACTIVE');
INSERT INTO COMPANY_EMP_MASTER VALUES (2, 'Karthik', 101, 50000, 'ACTIVE');
INSERT INTO COMPANY_EMP_MASTER VALUES (3, 'Meena', 102, 45000, 'ACTIVE');
INSERT INTO COMPANY_EMP_MASTER VALUES (4, 'John', 103, 40000, 'INACTIVE');
INSERT INTO COMPANY_EMP_MASTER VALUES (5, 'Priya', 104, 80000, 'ACTIVE');
INSERT INTO COMPANY_EMP_MASTER VALUES (6, 'Akhil', 103, 55000, 'ACTIVE');
commit;



